name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Docker Image to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        id: docker-login
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$password" | docker login -u "$username" --password-stdin
          echo "Login Successful"

      - name: Build Docker Image
        id: build-image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aayushkarclone:${{ github.sha }} .
          echo "Build Complete"

      - name: Push Docker Image to Docker Hub
        id: push-image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aayushkarclone:${{ github.sha }}
          echo "Image Pushed Successfully"